import { beforeEach, describe, expect, it } from 'vitest'
import { DEFAULT_CONFIG } from '../../lib/agentRl/engine'
import { useRlStore } from './rlStore'

const state = () => useRlStore.getState()
const round = () => {
  for (let i = 0; i < 6; i++) state().advance()
}
describe('Agent RL experiment lifecycle', () => {
  beforeEach(() => { state().configure(DEFAULT_CONFIG); state().setProductionFailure(0) })
  it('only updates parameters after computing reward and advantage', () => {
    const original = JSON.stringify(state().learner.policy)
    state().advance()
    state().advance()
    state().advance()
    expect(JSON.stringify(state().learner.policy)).toBe(original)
    expect(state().pending).toBeNull()
    state().advance()
    expect(state().pending?.policy).not.toEqual(state().learner.policy)
    state().advance()
    expect(state().learner.version).toBe(1)
    expect(state().sampler.version).toBe(0)
    state().advance()
    expect(state().sampler.version).toBe(1)
    expect(state().round).toBe(1)
    expect(state().productionVersion).toBe(0)
  })
  it('stale sampler is unchanged until explicit sync and blocks another on-policy round', () => {
    state().configure({ autoSync: false, rounds: 2 })
    const original = state().sampler
    round()
    expect(state().sampler).toBe(original)
    expect(state().learner.version).toBe(1)
    state().advance()
    expect(state().phase).toBe(0)
    expect(state().error).toContain('旧版本')
    state().syncSampler()
    state().advance()
    expect(state().batch.every((t) => t.policyVersion === 1)).toBe(true)
  })
  it('configuration changes reset curves, releases, weights, and usage', () => {
    round()
    state().configure({ groupSize: 12 })
    expect(state().history).toEqual([])
    expect(state().round).toBe(0)
    expect(state().trainingUsage.modelCalls).toBe(0)
    expect(state().checkpoints).toHaveLength(1)
    expect(state().canary).toBeNull()
  })
  it('repeated evaluation bills compute but never changes model weights', () => {
    round()
    const cp = JSON.stringify(state().learner)
    state().runTest()
    const first = state().evaluationUsage.modelCalls
    state().runTest()
    expect(state().evaluationUsage.modelCalls).toBeGreaterThan(first)
    expect(JSON.stringify(state().learner)).toBe(cp)
    expect(state().tests[0]).toBeDefined()
    expect(state().tests[1]).toBeDefined()
  })
  it('supports independent testing, paired canary, publish and rollback', () => {
    for (let i = 0; i < 40; i++) round()
    state().promote()
    expect(state().productionVersion).toBe(0)
    state().runTest()
    state().runCanary()
    expect(state().canary?.control.count).toBe(40)
    expect(state().canary?.candidate.count).toBe(40)
    expect(state().productionVersion).toBe(0)
    state().promote()
    expect(state().productionVersion).toBe(40)
    state().rollback()
    expect(state().productionVersion).toBe(0)
    expect(state().releases.at(-1)?.reward).toContain('verified')
  })
  it('invalidates canary when environment or selected version changes', () => {
    round()
    state().runCanary()
    state().setProductionFailure(0.9)
    expect(state().canary).toBeNull()
    state().runCanary()
    state().selectVersion(0)
    expect(state().canary).toBeNull()
  })
  it('protects the test set from training and keeps manual stop state', () => {
    state().setPlaying(true)
    state().setView('provider')
    expect(state().playing).toBe(false)
    round()
    expect(state().tests).toEqual({})
    expect(state().batch.every((t) => t.ticket.split === 'train')).toBe(true)
  })
})
